# Generated by Django 3.2.3 on 2021-06-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecproject', '0004_alter_accounts_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
