# Generated by Django 3.2.3 on 2021-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cybersecproject', '0005_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
    ]
