# Generated by Django 3.2.3 on 2021-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecproject', '0008_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
