# Generated by Django 3.2.3 on 2021-06-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybersecproject', '0009_posts_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='tags',
        ),
    ]
